
#version 460
#extension GL_GOOGLE_include_directive : require
#define SUPPORTED_RAY_QUERY
#define SUPPORTED_FLOAT_ATOM_ADD

#define RDV_STOCHASTIC_COMPUTE

#define LOCAL_SIZE_X 32
#define LOCAL_SIZE_Y 1
#define LOCAL_SIZE_Z 1

#define MAIN(tid) void rdv_compute(uvec3 tid)

void rdv_compute(uvec3 thread_id);

#include "core.h"

layout (local_size_x = LOCAL_SIZE_X, local_size_y = LOCAL_SIZE_Y, local_size_z = LOCAL_SIZE_Z) in;

layout(set=0, binding=0) uniform rdv_SystemInfo {
    uvec4 rdv_seeds;
    // total dimensions (not necessary the dispatch size if batched)
    int rdv_dim_x;
    int rdv_dim_y;
    int rdv_dim_z;
    // current batch offset
    int rdv_start_x;
    int rdv_start_y;
    int rdv_start_z;
};

layout(set=0, binding=3) uniform sampler rdv_samplers[2];
layout(set=1, binding=4) uniform texture1D rdv_textures_1D[1024];
layout(set=1, binding=5) uniform texture2D rdv_textures_2D[1024];
layout(set=1, binding=6) uniform texture3D rdv_textures_3D[1024];

void main()
{
    uvec3 global_id = gl_GlobalInvocationID;
    global_id += uvec3(rdv_start_x, rdv_start_y, rdv_start_z);
    if (any(greaterThanEqual(global_id, uvec3(rdv_dim_x, rdv_dim_y, rdv_dim_z))))
        return;
    #ifdef RDV_STOCHASTIC_COMPUTE
    int index = int(global_id.x + (global_id.z * rdv_dim_y + global_id.y) * rdv_dim_x);
    random_seed(random_spawn(rdv_seeds, index));
    #endif
    rdv_compute(global_id);
}


#define RDV_CODENAME ConstantMap_8
    layout(buffer_reference, scalar, buffer_reference_align=8) buffer MAP_BUFFER_NAME(RDV_CODENAME) {int rdv_kernel_id; 
int rdv_map_pad0; 
int rdv_map_pad1; 
int rdv_map_pad2; 
GPUPtr t; 
};
    struct RDV_CODENAME { MAP_BUFFER_NAME(RDV_CODENAME) data; };
    #define BW_USES_OUTPUT 1 
#define INPUT_DIM 3 
#define OUTPUT_DIM 1 
#define MAP_DECL in RDV_CODENAME _this 
#define parameters _this.data 
#include "system\push_signatures.h"
#include "map_const.h"

#include "system\pop_signatures.h"
#undef MAP_DECL
#undef RDV_CODENAME
#undef parameters
#undef BW_USES_OUTPUT
#undef INPUT_DIM
#undef OUTPUT_DIM

#define RDV_CODENAME CameraProbes_11
    layout(buffer_reference, scalar, buffer_reference_align=8) buffer MAP_BUFFER_NAME(RDV_CODENAME) {int rdv_kernel_id; 
int rdv_map_pad0; 
int rdv_map_pad1; 
int rdv_map_pad2; 
GPUPtr camera_poses; 
int num_cameras; 
float fov; 
float aspect_ratio; 
};
    struct RDV_CODENAME { MAP_BUFFER_NAME(RDV_CODENAME) data; };
    #define BW_USES_OUTPUT 1 
#define INPUT_DIM 3 
#define OUTPUT_DIM 6 
#define MAP_DECL in RDV_CODENAME _this 
#define parameters _this.data 
#include "system\push_signatures.h"
#include "perspective_camera_sensors.h"

#include "system\pop_signatures.h"
#undef MAP_DECL
#undef RDV_CODENAME
#undef parameters
#undef BW_USES_OUTPUT
#undef INPUT_DIM
#undef OUTPUT_DIM

#define RDV_CODENAME NanoVDBGrid3D_17
    layout(buffer_reference, scalar, buffer_reference_align=8) buffer MAP_BUFFER_NAME(RDV_CODENAME) {int rdv_kernel_id; 
int rdv_map_pad0; 
int rdv_map_pad1; 
int rdv_map_pad2; 
GPUPtr nvdb_data; 
int shape[3]; 
int align_corners; 
};
    struct RDV_CODENAME { MAP_BUFFER_NAME(RDV_CODENAME) data; };
    #define BW_USES_OUTPUT 1 
#define INPUT_DIM 3 
#define OUTPUT_DIM 1 
#define MAP_DECL in RDV_CODENAME _this 
#define parameters _this.data 
#include "system\push_signatures.h"
#include "nanovdb_grid3d.h"

#include "system\pop_signatures.h"
#undef MAP_DECL
#undef RDV_CODENAME
#undef parameters
#undef BW_USES_OUTPUT
#undef INPUT_DIM
#undef OUTPUT_DIM

#define RDV_CODENAME MultiplicationMap_18
    layout(buffer_reference, scalar, buffer_reference_align=8) buffer MAP_BUFFER_NAME(RDV_CODENAME) {int rdv_kernel_id; 
int rdv_map_pad0; 
int rdv_map_pad1; 
int rdv_map_pad2; 
NanoVDBGrid3D_17 map_a; 
ConstantMap_8 map_b; 
};
    struct RDV_CODENAME { MAP_BUFFER_NAME(RDV_CODENAME) data; };
    #define INPUT_DIM 3 
#define OUTPUT_DIM 1 
#define MAP_DECL in RDV_CODENAME _this 
#define parameters _this.data 
#include "system\push_signatures.h"
#include "map_op_mul.h"

#include "system\pop_signatures.h"
#undef MAP_DECL
#undef RDV_CODENAME
#undef parameters
#undef INPUT_DIM
#undef OUTPUT_DIM

#define RDV_CODENAME RaymarchingTransmittance_19
    layout(buffer_reference, scalar, buffer_reference_align=8) buffer MAP_BUFFER_NAME(RDV_CODENAME) {int rdv_kernel_id; 
int rdv_map_pad0; 
int rdv_map_pad1; 
int rdv_map_pad2; 
MultiplicationMap_18 extinction; 
float step_size; 
GPUPtr transform; 
};
    struct RDV_CODENAME { MAP_BUFFER_NAME(RDV_CODENAME) data; };
    #define INPUT_DIM 6 
#define OUTPUT_DIM 1 
#define MAP_DECL in RDV_CODENAME _this 
#define parameters _this.data 
#include "system\push_signatures.h"
#include "transmittance_rm.h"

#include "system\pop_signatures.h"
#undef MAP_DECL
#undef RDV_CODENAME
#undef parameters
#undef INPUT_DIM
#undef OUTPUT_DIM


            layout(binding=2, scalar, buffer_reference_align=8) uniform ComputeParameters {int rdv_kernel_id; 
int rdv_map_pad0; 
int rdv_map_pad1; 
int rdv_map_pad2; 
CameraProbes_11 probes_map; 
RaymarchingTransmittance_19 field_map; 
GPUPtr rdv_indices; 
GPUPtr output_tensor; 
int shape[3]; 
int sample_location[3]; 
int samples; 
} parameters;
            #define INDEX_DIM 3 
#define MAP_INPUT_DIM 6 
#define MAP_OUTPUT_DIM 1 
#include "capture_forward.h"

